#!/usr/bin/env node

/**
 * dungeetle is a little helper to bee
 */


console.log( "     _                   _               _   _" );
console.log( "  __| |_   _ _ __   __ _| |__   ___  ___| |_| | ___" );
console.log( " / _` | | | | '_ \\ / _` | '_ \\ / _ \\/ _ \\ __| |/ _ \\" );
console.log( "| (_| | |_| | | | | (_| | |_) |  __/  __/ |_| |  __/" );
console.log( " \\__,_|\\__,_|_| |_|\\__, |_.__/ \\___|\\___|\\__|_|\\___|" );
console.log( "                   |___/" );
console.log( "                                         dungbeetle 0.0.1 ");
console.log( "" );
console.log( "- dungbeetle is a little helper to bee build - " );
